### ISSUE TITLE
No data when I click on Execute or Get relations list

### ISSUE THREAD

**Issue by tassitano** [jorgediaz-lr/references-checker#2]
Hi, I successfully installed the latest version of the reference checker portlet on my JBoss server. Visually, everything is working fine and I see a message that says, "Your request completed successfully." when I click on the buttons.
When I consult the csv file, all I see is the header. There is no data. Is it possible that the portlet needs rights to speak to the database? I checked in the logs and I don't see any error or information allowing me to understand the problem.

Liferay version
Product information:

installation type: binary
build number: 6210
service pack version:
available SP version: Not available
installable SP version: Not available
patching-tool version: 1.0.24
time: 2020-07-03 12:20Z
plugins: Ehcache Cluster EE Web, Kaleo Designer EE Portlet, Kaleo Forms EE Portlet, Kaleo Workflow EE Web, Marketplace Portlet, References Checker Portlet, Solr 4 Search Engine EE-2.1.1-SUPPORT-DES-20190201142359842 Web, coherence-test-portlet Portlet, contexte-utilisateur-portlet Portlet, hook-ckeditor Hook, hook-healthcheck-deploy Hook, hook-journalisation Hook, hook-listepages-contenu Hook, hook-page-introuvable Hook, hook-permissions-deploy Hook, hook-profilage Hook, hook-versionnage Hook, infra-inventaire-portlet Portlet, journalisation-request-portlet Portlet, layouts-des-base Layouttpl, message-portlet Portlet, openid-test-portlet Portlet, openidconnect-hook Hook, portlet-healthcheck Portlet, portlet-wcms-detail Portlet, profilage Portlet, recherche-nouvelle-facette Hook, staging-details-publications-portlet Portlet, theme-des Theme, theme-ie8-des Theme, tranduction-hook Hook
Currently installed patches: hotfix-28341-6210

Application server
jboss-eap-6.1

Java version
java version "1.7.0_251"
Java(TM) SE Runtime Environment (build 1.7.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 24.251-b08, mixed mode)

Error
No error in logs

**Comment by tassitano** [comment]
Is it possible that the portlet needs rights to speak to the database?

**Comment by jorgediaz-lr** [comment]
Hi @tassitano 

Can you do the following actions?
1. Activate INFO traces to com.liferay.referenceschecker category
2. Test again both execute and get relations option
3. Attach the log file here?

Log levels are configured from Control Panel => Server Administration => Log levels section

You can drag and drop the log file to this issue and it will be attached. It is better than manually copying the log file content.

**Comment by tassitano** [comment]
Hi @jorgediaz-lr, 
com.liferay.referenceschecker category has been activated in INFO and the only information I found in the logs is as follows:


15:06:23,379 INFO  [http-executor-threads - 279][ReferencesCheckerPortlet:344] com.liferay.referenceschecker.portal.ModelUtilImpl is not available in classloader. Exception: com.liferay.referenceschecker.portal.ModelUtilImpl from [Module "deployment.references-checker-portlet.war:main" from Service Module Loader]
15:06:38,867 INFO  [http-executor-threads - 282][ReferencesCheckerPortlet:344] com.liferay.referenceschecker.portal.ModelUtilImpl is not available in classloader. Exception: com.liferay.referenceschecker.portal.ModelUtilImpl from [Module "deployment.references-checker-portlet.war:main" from Service Module Loader]
15:06:47,965 INFO  [http-executor-threads - 286][ReferencesCheckerPortlet:344] com.liferay.referenceschecker.portal.ModelUtilImpl is not available in classloader. Exception: com.liferay.referenceschecker.portal.ModelUtilImpl from [Module "deployment.references-checker-portlet.war:main" from Service Module Loader]

**Comment by tassitano** [comment]
Do you know what is the problem?

**Comment by jorgediaz-lr** [comment]
Hi @tassitano 

I am on holiday this week and I have limited access to the computer.

About your problem, It is a bit strange that the buttons are not doing anything. In order to get more information, can you repeat same operation but activating DEBUG traces?


1. Activate DEBUG traces to com.liferay.referenceschecker category
2. Test again both execute and get relations option
3. Attach the log file here

Regards,
Jorge

**Comment by tassitano** [comment]
Hi @jorgediaz-lr,
Bad news, I activated DEBUG traces to com.liferay.referenceschecker category and I have no other information:

08:37:29,581 INFO  [http-executor-threads - 407][ReferencesCheckerPortlet:344] com.liferay.referenceschecker.portal.ModelUtilImpl is not available in classloader. Exception: com.liferay.referenceschecker.portal.ModelUtilImpl from [Module "deployment.references-checker-portlet.war:main" from Service Module Loader]
08:37:48,117 INFO  [http-executor-threads - 412][ReferencesCheckerPortlet:344] com.liferay.referenceschecker.portal.ModelUtilImpl is not available in classloader. Exception: com.liferay.referenceschecker.portal.ModelUtilImpl from [Module "deployment.references-checker-portlet.war:main" from Service Module Loader]

**Comment by jorgediaz-lr** [comment]
Hi @tassitano 

Are you sure there are no other additional traces? 
In my code, there are other INFO traces before that ones you have copied that should be written to the log file.

Can you attach the log files?

Please check the log file of both `[LIFERAY_HOME]/logs` and `[LIFERAY_HOME]/jboss-x.x.x/standalone/log`

Thank you

PD: You can always try using the command line version of the tool, you will get ride of compatibility problems with JBoss and Liferay.

**Comment by tassitano** [comment]
Hi @jorgediaz-lr 
I checked in the two logs and I have no more information.
I will rather try references-checker-cmd-n.n.n.zip. Do I need to unzip it to a specific directory?
When I run ./references-checker -m | -r will that automatically generate a csv file?

**Comment by jorgediaz-lr** [comment]
About the portlet version, can you try executing again and:
 - Check browser console just in case there is a JavaScript error at button click time?
 - Attach a screenshot with the status of the portlet after click execute button?

About the command line version, it can be downloaded anywhere.
In the first run, it will ask you the information to connect to your database.

Thank you for your feedback

**Comment by jorgediaz-lr** [comment]
Hi @tassitano 

Were you able to use references checker successfully?

If you have any feedback, please let me know.

Thank you

**Comment by jorgediaz-lr** [comment]
I am closing this issue due to the inactivity
